version: '3.8'

services:
  web-monitor:
    container_name: website-monitor
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src           # Keep bind mount for development
      - website-storage:/app/src/storage  # Use a named volume for storage
    restart: unless-stopped

volumes:
  website-storage:  # Define the named volume
